name: Michele Myong
description: Personal website
menu:
 - page: About
   url: /about
 - page: Research 
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Teaching & Mentorship
   url: /teaching
 - page: Resume
   url: /resume
   links:
   - title: Experience
     url: "#experience"
   - title: Education
     url: "#education"
   - title: Positions
     url: "#positions"
 - page: Contact
   url: /contact


exclude:
 - _includes/sharing.html
 
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: michelemyong.github.io
locale: en_GB
