name: Michele Myong
description: Personal website
menu:
 - page: About
   url: /about
 - page: Research 
   url: /research
   links:
    - title: "Accelerator Science for Precision Measurements"
      url: "#acclerator-science-for-precision-measurements"
    - title: "Machine Learning for Chemical Discovery"
      url: "#project-two"
    - title: "Ultrafast Spectroscopy of Renewable Energy Materials"
      url: "#project-three"
    - title: "Future Research"
      url: "#project-four"
 - page: Teaching & Mentorship
   url: /teaching
 - page: Resume
   url: /resume
 - page: Contact
   url: /contact


exclude:
 - _includes/sharing.html
 
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: / 
locale: en_GB
